config/routes.rb
CurrentBooksBar::Application.routes.draw do

  root 'welcome#index'

  post '/update' => 'welcome#update'

  post '/map/update' => 'map#update'

  get '/legislators' => "representatives#index"

  get '/legislators/find_by_state' => "representatives#find_by_state"

  get '/legislators/show_by_state' => "representatives#show_by_state"

  get '/organizations/show_for_map' => "organizations#show_for_map"

  resources :organizations

  resources :locations

  get '/map' => "map#index"

  get '/zipcode' => "representatives#zipcode"

  get '/rerender' => "organizations#rerender"

  get '/mobile' => "mobile#index"

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    state_bar = State.all
    if request.xhr?
     render json: { bar_stats: state_bar }
    else
      render :index
    end
  end

  # REVIEW (RCB): Is this action used? I don't see a reference to it
  #   If not, I recommend removing the code and routes
  def update
        
    p state_obj = State.where(name: params[:state])


    p my_obj = state_obj[0]
    if request.xhr?
     render json: { stats: my_obj }
    end
  end
end

app/views/welcome/_explore.html.erb
<section id="anecdote">

    <h1 class='title center'>
  WHERE SHOULD THE AMERICAN TAXPAYERS<br> BE SPENDING THEIR MONEY?
  </h1>
  <div class="about">
  <p>
As much as 90% of juveniles who are sent to detention centers wind up back in the justice system.  Nationally, 60% of adults that are incarcerated will also return to prison.<hr>

What do we pay for these outcomes?  Taxpayers foot some shocking bills: around $40,000 to incarceate an adult and upwards of $200,000 to incarcerate a juvenile.  Meanwhile, our schools experiencing cuts - they are under-staffed, under-resourced.

We spend roughly $10,000 to educate a child per year.

What does this spending disparity say about us? <br><br> At BooksNotBars, we believe that we should aspire to flip the ratio.  We invite you to explore, get the facts, and take a stand.  use our action toolkit to send a msg to your local politicians or find ways to get involved in your neighborhood. <hr><p>

</section>

app/views/welcome/_facts.html.erb
<section id = 'facts'>
<div class="cover cover_gradient"></div>

  <div id = 'tileholder'>
    <div id='row1' class='row'>


      <div id='fact1' class="live-tile" data-mode="flip" data-delay="4000">
        <div class='front'>
          <span class="question">How much does Chicago spend on each inmate per year?</span>
        </div>
        <div class='back'>

            <p class="answerHead">$52,925</p>
            <p class="answerBody">...which is less than a THIRD of the cost in NYC:<br>$167k per inmate per year
            </p>
            <div class="factFoot">

              <p class="source">source: <a href="http://www.google.com">http://www.google.com</a></p>
              <span class="tweet">
                <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://booksnotbars.herokuapp.com" data-text="How much does Chicago spend on each inmate per year? $52,925!
    Find out more at" data-via="booksnotbars1" data-size="large" data-hashtags="booksnotbars">Tweet</a>
              </span>

            </div>
        </div>
      </div>


      <div id='fact2' class="live-tile" data-mode="flip" data-delay="4000">
        <div class='front'>
          <span class="question">How much has the rate of incarceration gone up in America since 1982?</span>
        </div>
        <div class='back'>

            <p class="answerHead">300%</p>
            <p class="answerBody">Since 2002, the United States has had the highest incarceration rate in the world, followed by Russia and Rwanda.
            </p>
          <div class="factFoot">

              <p class="source">source: <a href="http://www.prisonstudies.org/info/worldbrief/wpb_stats.php?area=all&category=wb_poprate">http://www.prisonstudies.org</a></p>
              <span class="tweet">
                <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://booksnotbars.herokuapp.com" data-text="Incarceration has gone up 300% in America since 1982!
    Find out more at" data-via="booksnotbars1" data-size="large" data-hashtags="booksnotbars">Tweet</a>
              </span>

          </div>
        </div>
      </div>
    </div>


    <div id='row2' class='row'>


      <div id='fact3' class="live-tile" data-mode="flip" data-delay="4000">
        <div class='front'>
          <span class="question">By what percent does 1 year of preschool reduce a child's odds of being incarcerated?</span>
        </div>
        <div class='back'>

          <p class="answerHead">40%</p>
          <p class="answerBody">At age 40, preschool attenders' incarceration rates are 28% vs. 52%, and 32% vs. 48% for violent crimes.
          </p>

          <div class="factFoot">

            <p class="source">source: <a href="http://evidencebasedprograms.org/1366-2/65-2">http://evidencebasedprograms.org</a></p>
            <span class="tweet">
              <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://booksnotbars.herokuapp.com" data-text="1 year of preschool reduces a child's odds of incarceration by 40%!
  Find out more at" data-via="booksnotbars1" data-size="large" data-hashtags="booksnotbars">Tweet</a>
            </span>

          </div>

        </div>
      </div>


      <div id='fact4' class="live-tile" data-mode="flip" data-delay="4000">
        <div class='front'>
          <span class="question">How many children could be enrolled in early learning programs for the cost of incarcerating 1 teen in juvenile detention?</span>
          </div>
        <div class='back'>

          <p class="answerHead">35</p>
          <p class="answerBody">Incrarcerating 1 teenager costs more than $200,000/year.<br>One year of early learning costs ≈$6,000.</p>

          <div class="factFoot">
            <p class="source">source: <a href="http://www.google.com">http://www.google.com</a></p>
            <span class="tweet">
              <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://booksnotbars.herokuapp.com" data-text="Juvie is 35 times more expensive than early learning programs.
  Learn more at" data-via="booksnotbars1" data-size="large" data-hashtags="booksnotbars">Tweet</a>
            </span>
          
          </div>

        </div>
      </div>
    </div>
  </div>


  <div class="nextZone" id="factsZone">
    <svg class="tick" xmlns="http://www.w3.org/2000/svg" version="1.1">
      <polygon points="0,0 150,0 75,50" style="fill:black;" opacity="0.9"/>
    </svg>
  </div>

</section>

app/views/welcome/_map.html.erb
 <section id="explore">
 <button id="close" value="close">close</button>
  <div  id="vmap" class="center"></div>

  <div id="typo_stats" class="center">
    <h1 id="state_info">Interactive Data Map</h1>
    <ul>
      <hr>
      <h3>Inmates by Ethinicity per 100,000</h3>
         <hr>
      <li>
      <h4>Caucasian</h4>
      <p id="whites_in_prison"></p>
      </li>
      <li>
      <h4>Latino</h4>
      <p id="latinos_in_prison"></p>
      </li>
      <li>
      <h4>African American</h4>
      <p id="blacks_in_prison"></p>
      </li>
    </ul>
  </div>

  <div class="stats">
    <ul>
      <li><h2 id="state">U.S.A </h2><p id="total_spending"></p></li>
      
      <li><h3>Spending Ratio</h3>
        <p id="spending_ratio">1</p>
      </li>
      
      <li><h3>Cost per pupil</h3>
        <p id="pupil_cost">10,000</p>
      </li>
      
      <li><h3>Cost per inmate</h3>
        <p id="inmate_cost">40,000</p>
      </li>
    
    </ul>
  
  </div>

  <div class="ranking">
    <ol class="center">
    <% states = State.order('spending_ratio DESC') %>
        <% states[10..20].each do |state| %>
          <% if state.spending_ratio %>
            <li id="state_name">
              <%=state.name%>: <span><%=state.spending_ratio%></span>
            </li>
          <% end %>
        <% end %>
      </ol>
    </div>

  <div id="chart_holder"></div>
<div id="bar_chart_holder"></div>
<!-- 
  <div class="nextZone" id="exploreZone">
    <svg class="tick" xmlns="http://www.w3.org/2000/svg" version="1.1">
      <polygon points="0,0 150,0 75,50" style="fill:rgba(218,33,50,1);"/>
    </svg>
  </div>
 -->
</section>

app/views/welcome/_overlay.html.erb
<div id ='overlay'></div>
<div id='specialBox'>
  <button id='agree'>I Agree!</button>
  <button id ='closeOverlay'>X</button>
</div>

app/views/welcome/_situation.html.erb
<section id='situation'>
  <div class="cover cover_gradient"></div>
  <div class="intro center">

    <h1 class="main">Books Not Bars</h1>
    <h2>Misplaced dollars and misplaced priorities.</h2>
    <hr>

    <div  id="reps">
      <%= form_tag("/legislators", method: "get") do %>
        <%= hidden_field_tag(:latitude) %>
        <%= hidden_field_tag(:longitude) %>
        <%= submit_tag "Share your Opinion", id: "contactReps", :class => 'submit_button'  %>
      <% end %>
    </div>
      <%= button_to "Take Action", organizations_path, :method => :get, :class => 'home_button' %>
      <div class="clearfix"></div>
      <hr>
  </div>
</section>

app/views/welcome/_state.html.erb
<section id="test">
  <div id="bar_chart_holder"></div>
</sectio>

app/views/welcome/_toolkit.html.erb
<section id = 'toolkit'>
  	<div id='toolkitPanel'>
	  	<div class="toolkitIcon" id="reps">
		    <%= form_tag("/legislators", method: "get") do %>
		      <%= hidden_field_tag(:latitude2) %>
		      <%= hidden_field_tag(:longitude2) %>
		      <%= image_submit_tag 'tweetCongressBlueOnWhite.png', id: "contactReps" %>
		    <% end %>

		    <div class="iconText" id="twCo"> Tweet Your Congressman </div>
	    </div>

	    <div class="toolkitIcon" id="orgs">
	    	<%= link_to image_tag('localActionBlueonWhite.png', :border=>0), {:action => 'index', :controller => 'organizations'}, :id => 'showOrgs' %>

	    	<div class="iconText"> Get Involved Locally </div>
	    </div>
  	</div>
</section>

app/views/welcome/index.html.erb
<section class ='content'>
    <%= render 'situation' %>
    <%= render 'map' %>
    
    <%= render 'explore' %>
    <%= render 'facts' %>
    <%= render 'toolkit' %>
</section>