config/routes.rb
CurrentBooksBar::Application.routes.draw do

  root 'welcome#index'

  post '/update' => 'welcome#update'

  post '/map/update' => 'map#update'

  get '/legislators' => "representatives#index"

  get '/legislators/find_by_state' => "representatives#find_by_state"

  get '/legislators/show_by_state' => "representatives#show_by_state"

  get '/organizations/show_for_map' => "organizations#show_for_map"

  resources :organizations

  resources :locations

  get '/map' => "map#index"

  get '/zipcode' => "representatives#zipcode"

  get '/rerender' => "organizations#rerender"

  get '/mobile' => "mobile#index"

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_format_of :website, :with => URI::regexp(%w(http https))
  validates_presence_of :title

  geocoded_by :address  # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates

  def address
    [address_street, city, state, zipcode].compact.join(', ')
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout 'location'

  def index
    @locations = Location.all.to_a
  end

  def create
    params.permit!
    @location = Location.new(params[:location])

    format_info_window_text(@location)

    @location.save

    redirect_to @location
  end

  def new
    @location = Location.new
  end

  # REVIEW(RCB): Error handling for locations that don't exist?
  def edit
    @location = Location.where(id: params[:id]).first
    if @location
      @location
    else
      redirect_to locations_path
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def update
    params.permit!
    @location = Location.find(params[:id])
    redirect_to @location
    @location = Location.where(id: params[:id]).first
    if @location
      @location.update(params[:location])
    else
      redirect_to locations_path
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to @location
  end

end

app/views/locations/_location_form.html.erb
<div class="locationForm">
<%= form_for @location, :html => {:class => "submitOrganizationLocation"} do |f| %>
  <p><%= f.label :title %> <%= f.text_field :title %></p>
  <p><%= f.label :organization_name %> <%= f.text_field :organization_name %></p>
  <p><%= f.label :address_street %> <%= f.text_field :address_street %><br />
  <p><%= f.label :city %> <%= f.text_field :city %> <%= f.label :state %> <%= f.text_field :state %> <%= f.label :zipcode %> <%= f.text_field :zipcode %></p>
  <p><%= f.label :description %> <%= f.text_area :description %></p>
  <p><%= f.label :website %> <%= f.url_field :website %></p>
  <p><%= f.label :twitter_handle %> <%= f.text_field :twitter_handle %></p>
  <p><%= f.submit :class => "submitOrganizationLocation" %></p>
<% end %>
</div>

app/views/locations/_location_utilities.html.erb
<div class="locationUtilities">
  <div class="utilities">
    <ul>
      <li><%= link_to "Dashboard", locations_path %></li>
      <li><%= link_to "Add new organization", new_location_path %></li>
      <li><%= link_to "Edit", edit_location_path(@location) %></li>
      <li><%= link_to "Delete", @location, :method => :delete, :confirm => "Are you sure?" %></li>
    </ul>
  </div>
</div>

app/views/locations/_new_location_form.html.erb
<%= form_for :location do |f| %>
  Title: <%= f.text_field :title %><br />
  Organization name: <%= f.text_field :organization_name %><br />
  Address: <%= f.text_field :address_street %><br />
  City: <%= f.text_field :city %> State: <%= f.text_field :state %> Zipcode: <%= f.text_field :zipcode %> <br />
  Description: <%= f.text_area :description %><br />
  Website: <%= f.url_field :website %><br />
  Twitter handle: <%= f.check_box :twitter_handle %><br />
  <%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<div class="locationEdit">
  <h1>Edit <%= @location.organization_name %></h1>
  <%= render 'location_form' %>
</div>

app/views/locations/index.html.erb
<div class="locationHome">
  <h1>Books Not Bars Organizations Manager</h1>
  <table>
    <th>Organization</th>
    <th>On Map?</th>
    <th>Edit</th>
    <th>Delete</th>
  <% @locations.each do |location| %>
  <tr>
    <td><%= location.organization_name %></td>
    <td><%= !location.latitude.nil? %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to "Delete", location, :method => :delete, :confirm => "Are you sure?" %></td>
  </tr>
  <% end %>
  </table>
</div>

app/views/locations/new.html.erb
<div class="newLocation">
  <h1>Add a new organization</h1>
  <p>Add a new organization location to the Books Not Bars database. With valid addresses or zipcodes, markers for these organizations will appear on the 'Get invoved' page.</p>
  <%= render 'location_form' %>
</div>

app/views/locations/show.html.erb
<div class="showLocation">
<h1><%= @location.title %></h1>
<ul>
  <li>Organization: <%= @location.organization_name %></li>
  <li>Address 1: <%= @location.address_street %></li>
  <li>Address 2: <%= "#{@location.city}, #{@location.state} #{@location.zipcode}" %></li>
  <li>Description: <%= @location.description %></li>
  <li>Website: <%= @location.website %></li>
  <li>Twitter: <%= @location.twitter_handle %></li>
</ul>
</div>